Repository PFCCLab/PaddleAPITest, pull requests merged in 2025-06, with the labels that each got.

#228 [BIT]回测问题修复：paddle.var
  tester/paddle_to_torch/mapping.json
  tester/paddle_to_torch/rules.py
Labels: contributor

#230 [BIT] fix augument paser bugs, update run-example.sh
  engineV2.py
  run-example.sh
Labels: contributor

#231 [BIT] Fix dtype_diff and grads_diff
  tester/accuracy.py
  tester/api_config/5_accuracy/accuracy_8.txt
  tester/api_config/5_accuracy/accuracy_gpu_error_dtype_diff.txt
  tester/base.py
  tester/paddle_to_torch/mapping.json
  tester/paddle_to_torch/rules.py
Labels: contributor

#236 [BIT] 回测修复 paddle.dot
  tester/api_config/config_analyzer.py
Labels: contributor

#240 [BIT] Update tools and README
  README.md
  tools/check_dup.py
  tools/error_stat.py
  tools/error_stat_0_size.py
  tools/error_stat_big_tensor.py
  tools/error_stat_split.py
  tools/get_api_config_set.py
  tools/get_api_set.py
  tools/log_digester_lite.py
  tools/retest_remover.py
  tools/skip_seeker.py
Labels: contributor

#244 [BIT] 回测问题修复：fix mode, move linalg.matrix_rank configs
  tester/accuracy.py
  tester/api_config/5_accuracy/accuracy_8.txt
  tester/api_config/5_accuracy/accuracy_cpu_error.txt
Labels: contributor

#243 [BIT] cpu回测修复
  tester/api_config/5_accuracy/accuracy_cpu_error.txt
  tester/paddle_to_torch/rules.py
Labels: contributor

#248 [BIT] Refine
  engineV2.py
  run-example.sh
  tester/paddle_to_torch/mapping.json
  tester/paddle_to_torch/rules.py
Labels: contributor

#252 [Accuracy diff No.151、154] Fix accuracy diff for vander fpn
  tester/accuracy.py
  tester/paddle_to_torch/rules.py
Labels: contributor

#253 [BIT] Add contiguous, fix numpy error
  tester/accuracy.py
  tester/api_config/log_writer.py
  tester/base.py
  tester/paddle_cinn_vs_dygraph.py
  tester/paddle_only.py
Labels: contributor

#256 [BIT] Add 5 test docs
  test_pipline/cpu_0size.md
  test_pipline/cpu_accuracy.md
  test_pipline/gpu_0size.md
  test_pipline/gpu_accuracy.md
  test_pipline/gpu_bigtensor.md
Labels: contributor

#255 [BIT] Update engineV2
  README.md
  engineV2-README.md
  engineV2.py
  run-example.sh
Labels: contributor

#259 [Accuracy diff No.138] Fix accuracy diff for paddle.sort API
  tester/api_config/2_paddle_only_random/random_calculation.txt
  tester/api_config/5_accuracy/accuracy_cpu_error.txt
Labels: contributor

#263 add test_cpu option in engine.py
  engine.py
Labels: HappyOpenSource

#268 Add kl_div grad config
  tester/accuracy.py
Labels: HappyOpenSource

#251 [Accuracy diff No.134] Fix accuracy diff for paddle.prod API
  tester/paddle_to_torch/rules.py
Labels: contributor, HappyOpenSource Pro

#273 [0-size Tensor Job2 No.59] Add 0-size Tensor support for gaussian_nll_loss
  tester/accuracy.py
Labels: contributor

#277 [Accuracy diff No.116] Fix accuracy diff for paddle.nn.functional.ctc_loss API
  tester/paddle_to_torch/rules.py
Labels: contributor

#279 [Accuracy diff No.122] Fix accuracy diff for paddle.nn.functional.kl_div API
  tester/api_config/5_accuracy/accuracy_gpu_error_grads_diff.txt
Labels: contributor

#285 [BIT] Fix fused_rotary_position_embedding to support bfloat16
  tester/api_config/config_analyzer.py
Labels: contributor

#289 [BIT] Warp old torch convert rule with Code() in rules.py
  tester/paddle_to_torch/rules.py
Labels: contributor

#276 [Accuracy diff No.25] Fix accuracy diff for paddle.linalg.eigh API
  tester/accuracy.py
  tester/base.py
Labels: contributor

#297 [0-size Tensor Job2 No.5] Add 0-size Tensor support for paddle.cdist
  tester/accuracy.py
  tester/api_config/5_accuracy/accuracy_gpu_error_grads_diff.txt
Labels: contributor

#295 [BIT] Support atol rtol param
  engine.py
  engineV2-README.md
  engineV2.py
  engineV3.py
  run-example.sh
  tester/accuracy.py
  tester/base.py
  tester/paddle_cinn_vs_dygraph.py
  tester/paddle_only.py
Labels: contributor

#283 [BIT] Change all List Comprehension to Regular Loop
  tester/paddle_to_torch/rules.py
Labels: contributor

#292 [Accuracy diff No.127] Fix accuracy diff for paddle.nn.functional.sigmoid_focal_loss API
  tester/accuracy.py
  tester/api_config/5_accuracy/accuracy_gpu_error_grads_diff.txt
  tester/api_config/config_analyzer.py
  tester/paddle_to_torch/rules.py
Labels: contributor

#309 doc: update `README.md` for repetitive accuracy_cpu_error.txt describution
  README.md
Labels: contributor

#320 [BIT] Fix paddle.Tensor.unflatten, format rules.py, base.py
  tester/api_config/config_analyzer.py
  tester/base.py
  tester/paddle_to_torch/rules.py
Labels: contributor

#314 [Accuracy diff No.53] Fix accuracy diff for paddle.rsqrt API
  report/ci_ce_gpu/test_history/20250319/error_log.log
Labels: contributor

#317 [Accuracy diff No.128] Fix accuracy diff for paddle.nn.functional.softmax_with_cross_entropy API
  tester/paddle_to_torch/rules.py
Labels: contributor

#330 [Accuracy diff No.23、24] Fix accuracy diff for paddle.linalg.cholesky_solve API
  tester/api_config/config_analyzer.py
Labels: contributor

#321 [BIT] Fix clip torch error when max and min is None
  tester/paddle_to_torch/rules.py
Labels: contributor

#333 [0-size Tensor No.55] Add 0-size Tensor support for expand
  report/0size_tensor_gpu/error_api_paddleonly.txt
  report/0size_tensor_gpu/error_config_paddleonly.txt
Labels: contributor

#342 [Accuracy diff No.97] Fix accuracy diff for paddle.incubate.softmax_mask_fuse API
  tester/accuracy.py
Labels: contributor

#332 [BIT] fix nn.functional.pad Tensor.__setitem__ nn.functional.cross_entropy
  tester/api_config/config_analyzer.py
  tester/paddle_to_torch/rules.py
Labels: contributor
